name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Make libft-mandatory
      run: make -C philo/libft LIBS=
    - name: Make libft-bonus
      run: make -C philo_bonus/libft LIBS=
    - name: Make philo
      run: make -C philo philo
    - name: Make philo_bonus
      run: make -C philo_bonus philo_bonus
